/* THEME */
export const THEME_CHANGE_TYPE = "THEME_CHANGE_TYPE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

/* Users */
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

// Message
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
export const SEND_MESSAGE_CLEAN_STATE = "SEND_MESSAGE_CLEAN_STATE";

export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAILURE = "GET_ALL_MESSAGES_FAILURE";
export const GET_ALL_MESSAGES_CLEAN_STATE = "GET_ALL_MESSAGES_CLEAN_STATE";

export const LET_DELETE_THE_MESSAGE = "LET_DELETE_THE_MESSAGE";
export const LET_DELETE_THE_MESSAGE_SUCCESS = "LET_DELETE_THE_MESSAGE_SUCCESS";
export const LET_DELETE_THE_MESSAGE_FAILURE = "LET_DELETE_THE_MESSAGE_FAILURE";
export const LET_DELETE_THE_MESSAGE_CLEAN_STATE =
  "LET_DELETE_THE_MESSAGE_CLEAN_STATE";

export * from "./auth";
export * from "./theme";
export * from "./message";
